syntax on
filetype on
color retrobox
set background=dark
set termguicolors
set title
set nocompatible
set nocursorline
set noswapfile
set nowrap
set wildmenu
set wildoptions=pum
set expandtab
set hlsearch
set ignorecase
set incsearch
set list
set listchars=tab:»\ ,trail:·,nbsp:␣
set number
set shiftwidth=2
set softtabstop=2
set tabstop=2
set path+=**
set formatoptions-=c
set formatoptions-=o
set formatoptions-=r
set backspace=indent,eol,start
set clipboard^=unnamed,unnamedplus
