colorscheme seafoam

set-option global grepcmd "rg -Hn --no-heading -i"
set-option global indentwidth 2
set-option global tabstop 2
set-option global scrolloff 1,3

add-highlighter global/ number-lines -hlcursor -separator " | "
add-highlighter global/ show-matching -previous

define-command fd -docstring "Fuzzy find files in current work directory" -params 1 %{ edit %arg{1} }
complete-command fd shell-script-candidates %{ fd -t f }

hook global RegisterModified '"' %{ nop %sh{
  case $(uname) in
    Linux)
      wl-copy -n "$kak_main_reg_dquote" > /dev/null 2>&1 & ;;
    Darwin)
      printf "%s" "$kak_main_reg_dquote" | pbcopy ;;
    esac
}}
